# Generated by Django 3.2.3 on 2022-03-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_emailform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='content',
            new_name='Description',
        ),
        migrations.DeleteModel(
            name='emailform',
        ),
    ]
